name: Consume changesets

on:
  # TODO: switch back to push
  # push:
  #   branches:
  #     - main
  #   tags-ignore:
  #     - v1.*
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      BUILD_ALL:
        description: whether certain steps should be run against all adapters
        required: false
        default: 'false'

jobs:
  consume-changesets:
    name: Consume changesets [NEW]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      UPSTREAM_BRANCH: 'HEAD~1'
      BUILD_ALL: ${{ github.event.inputs.BUILD_ALL }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Temporarily calculate changesets to generate readmes with proper versions
        run: |
          yarn changeset version
          git add -A
          git commit -m "Changesets mock"
      - name: Generate documentation
        run: |
          yarn generate:master-list -v
          yarn generate:readme -v
          git stash
      - name: Undo temporary changesets and commit docs
        run: |
          git reset head^ --hard
          git stash pop
          git add MASTERLIST.md
          git add "*README.md"
          yarn lint-staged
          git commit -m "Generated README(s)" # TODO: maybe this commit is unnecessary?
      - name: Increase monorepo version
        run: |
          BUMPED_VERSION=$(jq '.version | split(".")[1] | tonumber | . + 1 | tostring | "1." + . + ".0"' package.json)
          jq ".version = $BUMPED_VERSION" package.json > package.tmp.json
          mv package.tmp.json package.json
          echo "BUMPED_VERSION=$BUMPED_VERSION" >> $GITHUB_ENV
      - name: Commit changes and tag
        run: |
          git add package.json
          git commit -m "Bump monorepo version to $BUMPED_VERSION"
          git tag "v$BUMPED_VERSION"
      # - name: Create Release Pull Request
      #   uses: changesets/action@v1
      #   with:
      #     version: yarn changeset version
      #     title: '[WIP] Release v$BUMPED_VERSION'
      #     commit: '[WIP] Release v$BUMPED_VERSION'
