on:
  push:
    branches:
      - main
    tags:
      - v1.*

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  calculate-changes:
    name: Compute changed adapters
    runs-on: [self-hosted, sdlc-ghr-prod]
    outputs:
      adapter-list: ${{ steps.adapter-list.outputs.result }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up and install dependencies
        uses: ./.github/actions/setup
        with:
          skip-setup: true
      - name: Build list of changed packages
        id: changed-packages
        run: |
          echo "result=$( \
            yarn workspaces list -R --json --since=head^ \
            | jq -cs '.' \
            | jq -cr '[.[] | select(.location | startswith("packages"))]' \
          )" >> $GITHUB_OUTPUT
      - name: Build list of changed adapters
        id: adapter-list
        env:
          CHANGED_PACKAGES: ${{ steps.changed-packages.outputs.result }}
        run: |
          echo "result=$( \
            echo $CHANGED_PACKAGES \
            | jq -cr '{ \
                adapter: [ \
                  .[] \
                  | select( \
                    .location \
                    | startswith("packages/sources") \
                      or startswith("packages/composites") \
                      or startswith("packages/targets")) \
                    | .shortName = (.name | match("@chainlink/(.*)-adapter").captures[0].string) \
                ] \
              }' \
            )" >> $GITHUB_OUTPUT
